# Generated by Django 4.0.2 on 2022-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_img_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=70)),
                ('query', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
